- name: Add Node packages to yum  
  shell: curl -fsSL https://rpm.nodesource.com/setup_21.x | bash -

- name: Install Node.js
  yum:
    name: nodejs

- name: Copy sample app           
  copy:
    src: app.js
    dest: app.js

- name: Start sample app          
  shell: nohup node app.js &