apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-backend-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-app-backend-pods
    spec:
      serviceAccountName: sample-app-backend-service-account 
      containers:
        - name: sample-app-backend
          image: sample-app-backend:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
  selector:
    matchLabels:
      app: sample-app-backend-pods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app-backend-service-account                   

---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-backend-service
spec:
  type: ClusterIP
  selector:
    app: sample-app-backend-pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: security.istio.io/v1                             
kind: AuthorizationPolicy
metadata:
  name: sample-app-backend-allow-frontend
spec:
  selector:
    matchLabels:
      app: sample-app-backend-pods                           
  action: ALLOW
  rules:                                                     
  - from:
    - source:
        principals:
          - "cluster.local/ns/default/sa/sample-app-frontend-service-account"
    to:
    - operation:
        methods: ["GET"]
